"""add users oauth column

Revision ID: ead0be3dbfa6
Revises: 7e46a8afd030
Create Date: 2019-03-06 19:07:28.561423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead0be3dbfa6'
down_revision = '7e46a8afd030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_id', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_column('users', 'oauth_id')
    # ### end Alembic commands ###
